In [2]:
import numpy as np

In [3]:
O = np.array([0, 1, 1, 0]).reshape(-1, 1)

In [4]:
O

array([[0],
       [1],
       [1],
       [0]])

In [7]:
np.array([[-11.5, 9.5]]).reshape(-1,1)

array([[-11.5],
       [  9.5]])

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

X = np.array([[0, 0],
              [0, 1],
               [1, 0],
              [1, 1]])
O = np.array([0, 1, 1, 0]).reshape(-1, 1)

input_hidden_weights = np.array([[1.0, 5.0], [2.0, 6.0]])
hidden_output_weights = np.array([[-11.5], [9.5]]).reshape(-1,1)

def sigmoid_activation_function(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

lr = 0.1
epochs = 100

for epoch in range(epochs):
    print(epoch, end="\r", flush=True)
    for i in range(4):
        input_to_hidden = np.dot(X[i], input_hidden_weights).reshape(-1, 1)
        hidden_output = sigmoid_activation_function(input_to_hidden)
        
        input_to_output = np.dot(hidden_output.T, hidden_output_weights)
        output = sigmoid_activation_function(input_to_output)
        
        error = O[i] - output
        
        if abs(error) > 0:
            output_delta = error * sigmoid_derivative(output)
            # hidden_delta = np.dot(hidden_output_weights, output_delta.T).flatten() * sigmoid_derivative(hidden_output).flatten()
            hidden_delta = np.dot(hidden_output_weights, output_delta.T) * sigmoid_derivative(hidden_output)
            
            hidden_output_weights += lr * output_delta * hidden_output
            input_hidden_weights += lr * np.dot(X[i].reshape(-1, 1), hidden_delta.reshape(1, -1))

print("Final Predictions:")
for i in range(4):
    input_to_hidden = np.dot(X[i], input_hidden_weights).reshape(-1, 1)
    hidden_output = sigmoid_activation_function(input_to_hidden)
    input_to_output = np.dot(hidden_output.T, hidden_output_weights)
    output = sigmoid_activation_function(input_to_output)
    print(f"Input: {X[i]}, Output: {output[0][0]:.4f}, Target: {O[i][0]}")


Final Predictions:
Input: [0 0], Output: 0.2850, Target: 0
Input: [0 1], Output: 0.7121, Target: 1
Input: [1 0], Output: 0.7749, Target: 1
Input: [1 1], Output: 0.3503, Target: 0


In [2]:
input_hidden_weights

array([[0.98053484, 5.0192963 ],
       [1.14951114, 6.02150126]])

In [3]:
hidden_output_weights

array([[-11.51019454],
       [  9.67023153]])